language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install pytest pytest-cov pytest-dotenv
script:
  - export OPENWEATHERMAP_API_KEY
  - pytest -vv --cov --cov-report=term-missing
